name: CI WoogaGoogleMapsTests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser type for tests (chrome, firefox)"
        type: choice
        default: chrome
        options:
        - "chrome"
        - "firefox"
        - "edge"
        required: true

jobs:
  Test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore     

      - name: Build project
        run:
          dotnet build --configuration Release --no-restore
          
      - name: Run tests
        env:
          BROWSER_TYPE: ${{ github.event.inputs.browser }}
        run:
          dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx" --results-directory Reports/TestResults/   
          
      - name: Upload tests results
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: Publish test report
         path: "Reports/TestResults/TestResults.trx"
         reporter: dotnet-trx
         fail-on-error: false
